# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fraud.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'fraud.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66raud.proto\x12\x05\x66raud\"u\n\x12TransactionRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x12\n\naccount_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\x10\n\x08merchant\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\t\"Q\n\x13TransactionResponse\x12\x12\n\nrisk_score\x18\x01 \x01(\x01\x12\x10\n\x08\x64\x65\x63ision\x18\x02 \x01(\t\x12\x14\n\x0creason_codes\x18\x03 \x03(\t\"L\n\x12\x46lagAccountRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x12\n\nflagged_by\x18\x03 \x01(\t\"7\n\x13\x46lagAccountResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"(\n\x12RiskProfileRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\"[\n\x13RiskProfileResponse\x12\x12\n\nrisk_level\x18\x01 \x01(\t\x12\x14\n\x0crecent_flags\x18\x02 \x03(\t\x12\x1a\n\x12last_reviewed_date\x18\x03 \x01(\t2\xf8\x01\n\x15\x46raudDetectionService\x12I\n\x10\x43heckTransaction\x12\x19.fraud.TransactionRequest\x1a\x1a.fraud.TransactionResponse\x12\x44\n\x0b\x46lagAccount\x12\x19.fraud.FlagAccountRequest\x1a\x1a.fraud.FlagAccountResponse\x12N\n\x15GetAccountRiskProfile\x12\x19.fraud.RiskProfileRequest\x1a\x1a.fraud.RiskProfileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTIONREQUEST']._serialized_start=22
  _globals['_TRANSACTIONREQUEST']._serialized_end=139
  _globals['_TRANSACTIONRESPONSE']._serialized_start=141
  _globals['_TRANSACTIONRESPONSE']._serialized_end=222
  _globals['_FLAGACCOUNTREQUEST']._serialized_start=224
  _globals['_FLAGACCOUNTREQUEST']._serialized_end=300
  _globals['_FLAGACCOUNTRESPONSE']._serialized_start=302
  _globals['_FLAGACCOUNTRESPONSE']._serialized_end=357
  _globals['_RISKPROFILEREQUEST']._serialized_start=359
  _globals['_RISKPROFILEREQUEST']._serialized_end=399
  _globals['_RISKPROFILERESPONSE']._serialized_start=401
  _globals['_RISKPROFILERESPONSE']._serialized_end=492
  _globals['_FRAUDDETECTIONSERVICE']._serialized_start=495
  _globals['_FRAUDDETECTIONSERVICE']._serialized_end=743
# @@protoc_insertion_point(module_scope)
